### ISSUE TITLE
Kiuah without Systemd support

### ISSUE THREAD

**Issue by Mate76PL** [dw-0/kiauh#335]
### Is your feature request related to a problem? Please describe

Kiuah is often installed on old terminals. I'm installing on a Dell Wyse3040. I have to search a lot to find a version of Linux that is small enough to fit on an 8Gb emmc. The best in my opinion is AntiX. It is very light. Unfortunately, it does not support Systemd, so some Kiuah scripts get stuck. Is it possible to execute scripts without SystemD support?

### Describe the solution you'd like

Scripts without systemd

**Comment by th33xitus** [comment]
Please see: https://github.com/th33xitus/kiauh/issues/287

**Comment by The-Monkey-King** [comment]
I mean, it's going to barf, or at least stop, when it tries to run Klipper. And that's because Klipper is a service that uses systemd. You cannot get around it, period. It's what stopped me from using earlier versions of Windows Subsystem for Linux (WSL) because it did not employ systemd.

If anyone can rewrite Klipper from scratch to not use it, I am all ears/eyes.
