### ISSUE TITLE
Creating 8 instance but only can connect 6

### ISSUE THREAD

**Issue by dodolcool** [dw-0/kiauh#388]
### Linux Distribution

Linux mint

### What happened

![image](https://github.com/dw-0/kiauh/assets/26213488/d52d60a3-2514-477e-bdbc-711983a55769)
![image](https://github.com/dw-0/kiauh/assets/26213488/2a32570f-0e3f-49b2-bd75-42251757c174)
![image](https://github.com/dw-0/kiauh/assets/26213488/c3a821fe-f5c2-4924-be02-4396bbbc9825)

hello i install 8 klipper instance and moonraker and using mainsail but when adding the printer to mainsail i notice that only 6 instance active and cant connect to the other 2 instance.

### What did you expect to happen

i expected all instance active and can be used.
how to check if the instance really active or not and is it a way to force activate the instance?

### How to reproduce

install 8 instance then proceed like usual no special steps required.

Note: i really dont know if its bug or not but since there is no option to post an ask so i add this to bug

### Additional information

im using PC i3 gen 4 with 8gb ram

**Comment by dw-0** [comment]
Since 6 of 8 instances seem to run, i don't think there was an issue setting them up generally.
Instance 6 and 8 are affected it seems, you can try and restart them with the following command:
`sudo systemctl restart klipper-S1ProF` and `sudo systemctl restart klipper-S1ProH`

You can find out if they really startet with
`systemctl status klipper-S1ProF` and `systemctl restart klipper-S1ProH`

Something must be different to the other 6 instances, but as of now i can not tell what it is.

**Comment by dodolcool** [comment]
![image](https://github.com/dw-0/kiauh/assets/26213488/d67c8acd-db7e-483b-a3dc-1425439b6026)
![image](https://github.com/dw-0/kiauh/assets/26213488/2001bd1f-f19c-4290-a218-4de2b0f6a2a3)

since the error port is 7130 and 7132 i tried to check the status of F and H and the result is active.

**Comment by dw-0** [comment]
Okay, so Klipper is running fine.
Im sorry i forgot to also give you the commands to check if each Moonraker instance (whats actually matters) is active:
`systemctl status moonraker-S1ProF` and `systemctl status moonraker-S1ProH`

**Comment by dodolcool** [comment]
F
![image](https://github.com/dw-0/kiauh/assets/26213488/03ffdaa0-9902-4664-bef6-d3d24d224fb5)
H
![image](https://github.com/dw-0/kiauh/assets/26213488/1774824a-dd75-4a71-82c2-3c6a4ff19d93)

here's the result

**Comment by dw-0** [comment]
The second screenshot let me assume that there might be some other process already listening to the port (or ports)?
Try and use this command to see which ports are already in use: `sudo ss -tulpn | grep LISTEN`
Maybe we can see something.

**Comment by dodolcool** [comment]
![image](https://github.com/dw-0/kiauh/assets/26213488/a1b407f7-7fff-414f-9496-5d45891ac9de)

here's the result

**Comment by dw-0** [comment]
Doesn't look like it.
Please upload the klipper and moonraker log of those two instances.

**Comment by dodolcool** [comment]
well i cant access those two instance. when add the port to mainsail it will appear with this icon and cant press

![image](https://github.com/dw-0/kiauh/assets/26213488/1311d328-37a0-4804-95d2-8ad3ed199574)

is there any other way to pull the log?

**Comment by dw-0** [comment]
Yes there is, you can directly pull those logs from the file system by connecting to it with an SSH client. The logs are located in `~/printer-S1ProF/logs` and `~/printer-S1ProH/logs` then.

**Comment by dodolcool** [comment]
![image](https://github.com/dw-0/kiauh/assets/26213488/d3d38850-04ac-41f2-bbbf-df62276c422f)
i got this result and it same with H

**Comment by dw-0** [comment]
The easiest way might be to use a tool like Filezilla and then pull the logs with it.

**Comment by dodolcool** [comment]
[F.zip](https://github.com/dw-0/kiauh/files/12791030/F.zip)
[H.zip](https://github.com/dw-0/kiauh/files/12791052/H.zip)

here's the log i hope it can identify the troble.
also i notice that there's multiple folder with same name like shown below
![image](https://github.com/dw-0/kiauh/assets/26213488/ffea1177-173c-4841-bded-31397d0f0f52)

**Comment by dw-0** [comment]
Look closely, they are not the same names. Compared to Windows, file and foldernames on Linux are case-sensitive. So a folder called "folder" is a different folder than one with the name "Folder".

Maybe that is already the issue here... it seems that you must have installed klipper instances before?
Im not quite sure but maybe the best way would be to start out fresh. Make a backup of all relevant configurations, then remove all instances, remove all those folders, and install all instances fresh.
